DECLARE @LOGIN			SYSNAME
DECLARE @DB				SYSNAME
DECLARE @SQL			VARCHAR(MAX)
DECLARE @DB_OBJECTS		VARCHAR(512)

SET @LOGIN	= 'technossus'
SET @DB		= ''

SELECT @DB_OBJECTS = ' L.NAME AS LOGIN, U.NAME AS [USER], O.*
	FROM %D%.SYS.OBJECTS O
		INNER JOIN %D%.SYS.DATABASE_PRINCIPALS U
			ON COALESCE(O.PRINCIPAL_ID, (SELECT S.PRINCIPAL_ID FROM %D%.SYS.SCHEMAS S WHERE S.SCHEMA_ID = O.SCHEMA_ID))
				= U.PRINCIPAL_ID
		LEFT JOIN %D%.SYS.SERVER_PRINCIPALS L ON L.SID = U.SID

'

SELECT @SQL = 'SELECT * 
FROM (
	SELECT '+CAST(DATABASE_ID AS VARCHAR(9))+' AS DBID, ''MASTER'' AS DBNAME, '
		+ REPLACE(@DB_OBJECTS, '%D%', [NAME])
FROM master.sys.databases
WHERE [name] = 'master'

SELECT @SQL = @SQL + '	UNION ALL 

	SELECT '+CAST(DATABASE_ID AS VARCHAR(9))+', '''+[NAME]+''', '
	+ REPLACE(@DB_OBJECTS, '%D%', [NAME])
FROM master.sys.databases
WHERE [name] != 'master'

SELECT @SQL = @SQL + ') OO WHERE LOGIN = ''' + @LOGIN + ''''

PRINT @SQL
EXEC (@SQL)
